import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const output=new URL('../tmp/browser/',import.meta.url).pathname;
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
try{
 const page=await browser.newPage({viewport:{width:1512,height:1080},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8001');
 await page.getByText('DeepSeek 已配置',{exact:true}).waitFor();
 await page.locator('#fileInput').setInputFiles(new URL('../data/examples/fictional-tender.pdf',import.meta.url).pathname);
 await page.getByText('已提取 3 页',{exact:true}).waitFor({timeout:60000});
 await page.locator('#analyzeBtn').click();await page.getByRole('button',{name:'确认并分析',exact:true}).click();
 await page.getByText('服务要求',{exact:true}).waitFor({timeout:60000});
 await page.waitForTimeout(800);
 await page.screenshot({path:output+'test-analysis.png',fullPage:true});
 await page.getByRole('button',{name:'第 1 页',exact:true}).first().click();
 await page.getByRole('heading',{name:'原文依据',exact:true}).waitFor();
 await page.getByRole('button',{name:'PDF 第 1 页',exact:true}).click();
 await page.locator('#highlight').waitFor({state:'visible',timeout:10000});
 await page.getByRole('button',{name:'编辑 服务要求',exact:true}).click();
 await page.getByLabel('原文要求',{exact:true}).fill('人员配置：项目经理1名（人工编辑测试）');
 await page.getByRole('button',{name:'保存修改',exact:true}).click();
 await page.getByText('人员配置：项目经理1名（人工编辑测试）',{exact:true}).waitFor();
 await page.getByRole('tab',{name:/评分要求/}).click();
 await page.getByText('80分',{exact:true}).waitFor();
 await page.getByRole('tab',{name:/废标红线/}).click();
 await page.screenshot({path:output+'test-risks.png',fullPage:true});
 await page.locator('#generateBtn').click();await page.getByRole('button',{name:'确认并生成',exact:true}).click();
 await page.getByRole('heading',{name:'质量管理',exact:true}).waitFor({timeout:60000});
 await page.waitForTimeout(1800);
 await page.getByRole('button',{name:'编辑章节',exact:true}).first().click();
 await page.locator('#modalBody textarea').first().fill('本章内容由人工编辑。企业名称：【待补充：企业名称】。');
 await page.getByRole('button',{name:'保存章节',exact:true}).click();
 await page.getByText('本章内容由人工编辑。企业名称：【待补充：企业名称】。',{exact:true}).waitFor();
 await page.screenshot({path:output+'test-draft.png',fullPage:true});
 const downloaded=page.waitForEvent('download');await page.locator('#exportBtn').click();
 const download=await downloaded;await download.saveAs(output+'test-export.docx');
 await page.setViewportSize({width:390,height:844});await page.locator('#showResult').click();
 await page.screenshot({path:output+'test-mobile-draft.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile overflow');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log(JSON.stringify({result:'passed',mode:'isolated model fixture, not live DeepSeek',errors,export:output+'test-export.docx'}));
}finally{await browser.close();}
