import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8000';
const output=new URL('../tmp/browser/',import.meta.url).pathname;
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
const page=await browser.newPage({viewport:{width:1512,height:1080},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto(base);await page.getByText('DeepSeek 未配置',{exact:true}).waitFor();
await page.screenshot({path:output+'desktop-empty.png',fullPage:true});
await page.getByRole('button',{name:'企业资料',exact:true}).click();
await page.locator('[name="name"]').fill('虚构演示企业（测试用）');
await page.locator('[name="capabilities"]').fill('本条为本地 UI 测试资料，不属于真实客户。');
await page.locator('[name="is_demo"]').check();
await page.getByRole('button',{name:'保存资料',exact:true}).click();
await page.getByText('企业资料已保存到本机。',{exact:true}).waitFor();
await page.getByRole('button',{name:'标书工作台',exact:true}).click();
await page.locator('#fileInput').setInputFiles(new URL('../data/examples/fictional-tender.pdf',import.meta.url).pathname);
await page.getByText('已提取 3 页',{exact:true}).waitFor({timeout:60000});
await page.waitForTimeout(600);
if(!await page.locator('#analyzeBtn').isDisabled())throw new Error('Missing API key must disable analysis');
const pixels=await page.locator('#pdfCanvas').evaluate(canvas=>{
 const c=canvas.getContext('2d'),data=c.getImageData(0,0,canvas.width,canvas.height).data;let dark=0;
 for(let i=0;i<data.length;i+=4)if(data[i]<180&&data[i+1]<180&&data[i+2]<180)dark++;return dark;
});
if(pixels<1000)throw new Error('PDF canvas appears blank');
await page.screenshot({path:output+'desktop-document.png',fullPage:true});
await page.getByRole('button',{name:'下一页',exact:true}).click();
await page.waitForTimeout(300);
if(await page.locator('#pageNumber').inputValue()!=='2')throw new Error('Page navigation failed');
await page.getByRole('button',{name:'提取文本',exact:true}).click();
await page.getByRole('heading',{name:'提取文本',exact:true}).waitFor();
await page.locator('#modalClose').click();
await page.getByRole('button',{name:'运行状态',exact:true}).click();
await page.screenshot({path:output+'desktop-settings.png',fullPage:true});
await page.getByRole('button',{name:'标书工作台',exact:true}).click();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(600);
await page.screenshot({path:output+'mobile-document.png',fullPage:true});
await page.locator('#showResult').click();await page.screenshot({path:output+'mobile-result.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Mobile horizontal overflow');
await page.setViewportSize({width:1280,height:900});await page.waitForTimeout(300);
await page.screenshot({path:output+'desktop-1280.png',fullPage:true});
if(errors.length)throw new Error(errors.join('\n'));
console.log(JSON.stringify({result:'passed',pdfDarkPixels:pixels,screenshots:output,errors}));
await browser.close();
